FROM golang:1.10.3-stretch

COPY . /go/src/github.com/miatachallenge/bridge/server
RUN go install -v github.com/miatachallenge/bridge/server

FROM debian:stretch
COPY --from=0 /go/bin/server /usr/bin/server
